services:
  site-monitor:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-dev}
    env_file:
      - .env
    volumes:
      - "./configs/sites.yaml:/configs/sites.yaml:ro"
    restart: unless-stopped
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - monitor-network

  postgres:
    image: postgres:17-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - site-monitor-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - monitor-network

networks:
  monitor-network:
    driver: bridge

volumes:
  site-monitor-postgres-data:
