# Этап 1: сборка приложения
FROM golang:1.26-alpine AS builder

ARG VERSION=dev

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build \
    -trimpath \
    -ldflags="-s -w -X github.com/ViktorNikolaevichD/site-monitor/internal/notification/buildinfo.Version=${VERSION}" \
    -o /build/notification \
    ./cmd/notification

# Этап 2: запуск приложения
FROM alpine:3.22 AS runtime

ARG VERSION=dev

LABEL org.opencontainers.image.title="notification" \
      org.opencontainers.image.description="Notification service" \
      org.opencontainers.image.source="https://github.com/ViktorNikolaevichD/site-monitor" \
      org.opencontainers.image.version="${VERSION}"

RUN apk add --no-cache ca-certificates \
    && adduser -D -H -u 10001 app

WORKDIR /app

COPY --from=builder /build/notification ./notification

USER app

EXPOSE 8081

ENTRYPOINT ["./notification"]
