FROM golang:1.26-alpine AS builder

ARG GOOSE_VERSION=v3.27.2
ARG GOOSE_TAGS=no_clickhouse,no_libsql,no_mssql,no_mysql,no_sqlite3,no_vertica,no_ydb

RUN CGO_ENABLED=0 go install -tags="${GOOSE_TAGS}" github.com/pressly/goose/v3/cmd/goose@${GOOSE_VERSION}

FROM alpine:3.22

RUN apk add --no-cache ca-certificates

COPY --from=builder /go/bin/goose /usr/local/bin/goose
COPY migrations /migrations
COPY docker/migrate-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["up"]
