# Этап 1: сборка приложения
FROM golang:1.26-alpine AS builder

ARG VERSION=dev

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build \
    -trimpath \
    -ldflags="-s -w" \
    -o /build/gateway \
    ./cmd/gateway

# Этап 2: запуск приложения
FROM alpine:3.22 AS runtime

ARG VERSION=dev

LABEL org.opencontainers.image.title="gateway" \
      org.opencontainers.image.description="Gateway service" \
      org.opencontainers.image.source="https://gitlab.com/Dokuchaevvn/site-monitor" \
      org.opencontainers.image.version="${VERSION}"

RUN apk add --no-cache ca-certificates \
    && adduser -D -H -u 10001 app

WORKDIR /app

COPY --from=builder /build/gateway ./gateway

USER app

EXPOSE 8082

ENTRYPOINT ["./gateway"]

CMD ["-config", "/configs/gateway.yaml"]
