sites:
  - url: https://vk.com
    name: VK
  - url: https://vk.ru
    name: VK RU
  - url: https://viniapps.ru
    name: ВиНи Аппс RU
  - url: https://viniapps.com
    name: ВиНи Аппс COM
  - url: https://google.com
    name: Google
  - url: https://yandex.ru
    name: Яндекс
  - url: https://habr.com
    name: Habr
  - url: https://youtube.com
    name: YouTube
  - url: https://abrakadabra.ru
    name: Abrakadabra
  - url: https://kremlin.ru
    name: Кремль
interval: 60s
http_addr: :8080
log_level: info
http_timeout: 10s
database:
  max_conns: 10
  min_conns: 2
  max_conn_lifetime: 1h
  max_conn_idle_time: 30m
  connect_timeout: 5s
  query_timeout: 3s
