sites:
  - url: https://vk.com
    name: VK
  - url: https://vk.ru
    name: VK RU
  - url: https://viniapps.ru
    name: ВиНи Аппс RU
  - url: https://viniapps.com
    name: ВиНи Аппс COM
  - url: https://google.com
    name: Google
  - url: https://yandex.ru
    name: Яндекс
  - url: https://habr.com
    name: Habr
  - url: https://youtube.com
    name: YouTube
  - url: https://abrakadabra.ru
    name: Abrakadabra
  - url: https://kremlin.ru
    name: Кремль
interval: 60s
http_addr: :8080