// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Возвращает статус, uptime, текущее время и версию приложения",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Проверить готовность к работе",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор запроса для трассировки",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.HealthResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Идентификатор запроса"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/dto.HealthResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Идентификатор запроса"
                            }
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Возвращает pong, если HTTP-сервер работает",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Проверить доступность сервиса",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор запроса для трассировки",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PingResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Идентификатор запроса"
                            }
                        }
                    }
                }
            }
        },
        "/sites": {
            "get": {
                "description": "Возвращает все сайты, добавленные в мониторинг",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sites"
                ],
                "summary": "Получить список сайтов",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор запроса для трассировки",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.SiteResponse"
                            }
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Идентификатор запроса"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Создаёт новый сайт для мониторинга",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sites"
                ],
                "summary": "Добавить сайт",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор запроса для трассировки",
                        "name": "X-Request-ID",
                        "in": "header"
                    },
                    {
                        "description": "Данные сайта",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddSiteRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.SiteResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Идентификатор запроса"
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректный JSON, URL или имя сайта",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Идентификатор запроса"
                            }
                        }
                    },
                    "409": {
                        "description": "Сайт с таким URL уже существует",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Идентификатор запроса"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Идентификатор запроса"
                            }
                        }
                    }
                }
            }
        },
        "/sites/{id}": {
            "delete": {
                "description": "Удаляет сайт из мониторинга по UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sites"
                ],
                "summary": "Удалить сайт",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор запроса для трассировки",
                        "name": "X-Request-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID сайта",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Сайт удалён",
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Идентификатор запроса"
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректный UUID сайта",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Идентификатор запроса"
                            }
                        }
                    },
                    "404": {
                        "description": "Сайт не найден",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Идентификатор запроса"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Идентификатор запроса"
                            }
                        }
                    }
                }
            }
        },
        "/sites/{id}/status": {
            "get": {
                "description": "Возвращает результат последней проверки сайта по UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sites"
                ],
                "summary": "Получить статус сайта",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор запроса для трассировки",
                        "name": "X-Request-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID сайта",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.StatusResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Идентификатор запроса"
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректный UUID сайта",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Идентификатор запроса"
                            }
                        }
                    },
                    "404": {
                        "description": "Сайт не найден",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Идентификатор запроса"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Идентификатор запроса"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AddSiteRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Example"
                },
                "url": {
                    "type": "string",
                    "example": "https://example.com"
                }
            }
        },
        "dto.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/health.Status"
                        }
                    ],
                    "example": "healthy"
                },
                "time": {
                    "type": "string",
                    "example": "2026-07-15T13:03:26.9795475+03:00"
                },
                "uptime": {
                    "type": "integer",
                    "example": 729028
                },
                "version": {
                    "type": "string",
                    "example": "v1.0.0"
                }
            }
        },
        "dto.PingResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "pong"
                }
            }
        },
        "dto.SiteResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "name": {
                    "type": "string",
                    "example": "Example"
                },
                "url": {
                    "type": "string",
                    "example": "https://example.com"
                }
            }
        },
        "dto.StatusResponse": {
            "type": "object",
            "properties": {
                "availability": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/site.Availability"
                        }
                    ],
                    "example": "available"
                },
                "checked_at": {
                    "type": "string",
                    "example": "2026-07-15T10:00:00Z"
                },
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "duration": {
                    "type": "integer",
                    "example": 245
                },
                "error": {
                    "type": "string",
                    "example": "context deadline exceeded"
                },
                "url": {
                    "type": "string",
                    "example": "https://example.com"
                }
            }
        },
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "некорректный запрос"
                }
            }
        },
        "health.Status": {
            "type": "string",
            "enum": [
                "healthy",
                "unhealthy"
            ],
            "x-enum-varnames": [
                "StatusHealthy",
                "StatusUnhealthy"
            ]
        },
        "site.Availability": {
            "type": "string",
            "enum": [
                "available",
                "unavailable",
                "unknown"
            ],
            "x-enum-varnames": [
                "Available",
                "Unavailable",
                "Unknown"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Site Monitor API",
	Description:      "REST API для управления сайтами и просмотра результатов мониторинга.\nОпционально передавайте X-Request-ID в запросе; сервис вернёт его (или сгенерированный ID) в заголовке ответа X-Request-ID.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
